name: CI

on:
  workflow_call:
  pull_request:
  push:
    branches: [develop]

jobs:
  pre_commit_checks:
    name: 🚴 Pre-Commit checks 🚴
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv 
        uses: astral-sh/setup-uv@v5

      - name: Install pre-commit hooks
        run: uv run pre-commit install  

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files  
