name: CI

on:
  workflow_call:
  pull_request:
  push:
    branches: [develop]

jobs:
  pre_commit_checks:
    name: 🚴 Pre-Commit checks 🚴
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install the latest version of uv
      - name: Install the latest version of uv 
        uses: astral-sh/setup-uv@v5

      # Install `pre-commit` in the `uv` virtual environment
      - name: Install pre-commit
        run: uv run pip install pre-commit

      # Install pre-commit hooks
      - name: Install pre-commit hooks
        run: uv run pre-commit install  

      # Run pre-commit hooks on all files
      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files  
